narwhal/config/routes.rb
Rails.application.routes.draw do
  
  resources "posts", only: [:index, :show]

  root 'static_pages#index'
  
  StaticPagesController.action_methods.each do |action|
    get "/#{action}", to: "static_pages##{action}", as: "#{action}"
  end
  
  resources "contacts", only: [:new, :create]

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

narwhal/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

narwhal/app/models/contact.rb
class Contact < ActiveRecord::Base
  
  include MailForm::Delivery
  
  validates :name, :email, :message, presence: true
  
  append :remote_ip, :user_agent, :session
  
      attribute :name,      :validate => true
      attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
      attribute :message

      def headers
        {
          :subject => "My Contact Form",
          :to => "grillopress@gmail.com",
          :from => %("#{name}" <#{email}>)
        }
      end
    
end

narwhal/app/models/post.rb
class Post < ActiveRecord::Base
    # t.string   "title"
    # t.string   "image"
    # t.string   "author"
    # t.text     "body"

  validates :title, :author, :body, presence: true

end

narwhal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

narwhal/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    
    if @contact.save
       @contact.deliver
       flash.now[:error] = nil
       flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
  
end

narwhal/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  
end

narwhal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end
  
end

narwhal/app/helpers/application_helper.rb
module ApplicationHelper
end

narwhal/app/helpers/contacts_helper.rb
module ContactsHelper
end

narwhal/app/helpers/posts_helper.rb
module PostsHelper
end

narwhal/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

narwhal/app/views/application/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <%= link_to 'Admin Panel', admin_root_path, class: "btn btn-link pull-right" %>
    </div>
  </div>

</footer>

narwhal/app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Tern</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'News', posts_path %></li>  
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <!-- Insert admin or whatevs links here -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

narwhal/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

narwhal/app/views/contacts/new.html.erb
  <h1>Contact</h1>
  <%= form_for @contact do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :message %>
    </div>

    <div class="form-actions">
      <%= f.submit %>
    </div>
  <% end %>

narwhal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tern</title>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  
</head>
<body>

  <%= render 'navbar' %>
  
<%= yield %>

  <%= render 'footer' %>
</body>
</html>

narwhal/app/views/posts/_sidebar.html.erb
<div class="well">
  <h2>Hello!</h2>
  <p>This is a paragraph in the sidebar. The sidebar is meant to ensure that you have generic things in your news section.</p>
</div>

<div class="well">
  
</div>

narwhal/app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <header><h1>News</h1></header>
    </div>
    
    
    <div class="col-md-8">
      <% @posts.each do |p| %>
  
       <article class="well" id="post-<%= p.id %>">
         <h2><%= p.title %></h2>
        <%= link_to 'Read more', post_path(p), class: "btn btn-primary" %>
      </article>
        

      <% end %>
    </div>
    
    <div class="col-md-4" role="aside">
      <%= render 'sidebar' %>
    </div>
    
  </div>
</div>

narwhal/app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <header><h1><%= @post.title %></h1></header>
    </div>
    
    <div class="col-md-8" role="main">
      <article id="post-<%= @post.id %>">
        <section class="well" id="article-main">
          <p><%= @post.author %></p>

             <%= @post.body %>
        </section>

      
        <footer><%= link_to 'Back', posts_path, class: "btn btn-primary" %></footer>
      </article>
    </div>
    
    <div class="col-md-4" role="aside">
      <%= render 'sidebar' %>
    </div>

    
    
  </div>
</div>

narwhal/app/views/static_pages/index.html.erb
<section class="site-banner">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Tern - A Rails CMS Starter Template</h1>
      </div>
    </div>
  </div>
</section>